format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$time\
$line_break\
$shell\
$character
"""

[fill]
symbol = " "

[directory]
style = "cyan"
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
style = "green"

[git_status]
style = "yellow"

[time]
disabled = false
format = " [$time]($style) "
style = "cyan"

[cmd_duration]
format = " [$duration]($style)"
style = "yellow"

[java]
format = "[${symbol}(${version} )]($style)"

[kotlin]
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version)]($style)"

[lua]
format = "[$symbol($version )]($style)"
