format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$time\
$line_break\
$shell\
$character
"""

[fill]
symbol = " "

[directory]
style = "blue"
truncate_to_repo = false
read_only = " "

[git_branch]
format = "[$symbol$branch]($style) "
style = "green"
symbol = " "

[git_status]
style = "yellow"

[time]
disabled = false
format = " [$time]($style) "
style = "cyan"

[cmd_duration]
format = " [$duration]($style)"
style = "yellow"

[kotlin]
format = " [$symbol($version)]($style)"

[nodejs]
format = "[$symbol($version)]($style)"
symbol = " "

[lua]
format = "[$symbol($version)]($style)"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
format = "[${symbol}(${version})]($style)"
symbol = " "


[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
format = "[$symbol($version)]($style)"
symbol = " "

[rust]
format = "[$symbol($version)]($style)"
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
