Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
